version: '3'

services:
  backend-challenge:
    image: openjdk:11
    container_name: backend-challenge
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom